services:
  pgdb:
    image: postgres:14
    container_name: 58-Warehouse-bot
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: superadmin_password
      POSTGRES_DB: warehouse_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata: