services:
  pgdb:
    image: postgres:14
    container_name: 57-Promotions-bot
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: superadmin
      POSTGRES_PASSWORD: superadminPassword123
      POSTGRES_DB: promotions_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata: